### PR TITLE
Create Lime Gen 3 Motor Controller Readout disassembled.ASM

### PR DESCRIPTION
**Pull request by M20001**
This ist the disassembled version of the .HEX from the Motor Controller like the .hex, if you can read it, here you go.

### CODE REVIEW

**Comment by oneohtrix** [comment]
Thanks for the contribution! 

I have a request, if you have an SJ3, could you please take some external/internal photos?
What ESC model is being used, etc?

**Comment by M20001** [comment]
Hello, I have a few photos, i can send you the Photos, i will make more photos if i have time.
The Motor controller is potted, i removed the Potting material, and know now there is a STM32F103C8T6 inside. The Mosfets are ST110N7F6, there is a 4 Pin Falshing port in the Controller, the Processor is not locked. Here the Photos:
[img]https://i.imgur.com/7A93lVD.jpg[/img]
[img]https://i.imgur.com/nUzxONl.jpg[/img]
[img]https://i.imgur.com/SgZUp8P.jpg[/img]
[img]https://i.imgur.com/kXgUQGc.jpg[/img]
[img]https://i.imgur.com/cVvcmHb.jpg[/img]
[img]https://i.imgur.com/SvAE2Zt.jpg[/img]
[img]https://i.imgur.com/5HhSmEv.jpg[/img]
[img]https://i.imgur.com/7EgFrek.jpg[/img]
The more interesting Part of the Scooter is the green Box, if we can hack the Software on the Box, we are able to unlock the Scooter for example by SMS to a personal SIM Card in the Scooter. The green Box has three connectors, two of them are connected in the Scooter, the third one, the green one with 5pins is a service connector, it is not connected in the scooter, und i think you can acces the Software over this connector, but i do not know the Pinout. Sorry for bad english, i come from Germany i am better in reverse engineerin than speaking english...

**Comment by M20001** [comment]
Here this is inside the Green Box, a black box, in this black box is a green Board:
[img]https://i.imgur.com/PnZ4RDY.jpg[/img]
[img]https://i.imgur.com/fPvKHRH.jpg[/img]
[img]https://i.imgur.com/Bw3gSp6.jpg[/img]
[img]https://i.imgur.com/xBlSwNe.jpg[/img]
[img]https://i.imgur.com/VOVAxBB.jpg[/img]
[img]https://i.imgur.com/JzX50lC.jpg[/img]

**Comment by M20001** [comment]
Here the Board without the antennas:
[img]https://i.imgur.com/Not8bcf.jpg[/img]

**Comment by M20001** [comment]
Here the controller and wiring in the under case:
[img]https://i.imgur.com/gNCmaGR.jpg[/img]
[img]https://i.imgur.com/nuvH1Gp.jpg[/img]
[img]https://i.imgur.com/4oswWxG.jpg[/img]
[img]https://i.imgur.com/h4oC3LX.jpg[/img]
[img]https://i.imgur.com/fAZHGa2.jpg[/img]
[img]https://i.imgur.com/FhSGUAc.jpg[/img]
[img]https://i.imgur.com/a0MTSJE.jpg[/img]
[img]https://i.imgur.com/xirlWKx.jpg[/img]
[img]https://i.imgur.com/fFfQGnX.jpg[/img]
[img]https://i.imgur.com/DRfQmEV.jpg[/img]
[img]https://i.imgur.com/3gYuHFl.jpg[/img]
[img]https://i.imgur.com/7C9EZWU.jpg[/img]
[img]https://i.imgur.com/WyxIu7Z.jpg[/img]
[img]https://i.imgur.com/45xou2E.jpg[/img]

**Comment by viktor76525** [comment]
Hi, not sure if you are interested in what I have done (reverse engineer display module for 2.5).
Couldn't find contact.
Available here:
https://github.com/viktor76525/micro/tree/master/scooter_display

**Comment by M20001** [comment]
Hello,

 

Its always intersting to see reversing about Lime scooters, but I cannot test it, because I am in Germany, there

are no Lime Gen 2.5, only gen 3. Can you take a look sometime on the Software from the motor controller from the lime gen 3

I have posted? I want to make the Scooter a little bit stronger, but to do that, you have to set the motor current higer, and this is only possible if its possible to modify the software in this way.

 

Best Regards Elias

 
 

Gesendet: Donnerstag, 16. April 2020 um 13:00 Uhr
Von: "Viktor Polak" <notifications@github.com>
An: "oneohtrix/lime-scooter-reversing" <lime-scooter-reversing@noreply.github.com>
Cc: "M20001" <bastler2117@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [oneohtrix/lime-scooter-reversing] Create Lime Gen 3 Motor Controller Readout disassembled.ASM (#6)


 

Hi, not sure if you are interested in what I have done (reverse engineer display module for 2.5).
Couldn't find contact.
Available here:
https://github.com/viktor76525/micro/tree/master/scooter_display

**Comment by xeromem2020** [comment]
hey, has anyone made any progress on the combox or any of the the other components on the gen3 scooters?

**Pull request merged**
